{"uuid": "a5202d8f-73cf-4727-a0d7-b6b215882288", "children": ["ea1e6333-2ed8-4dfd-b21d-e387f5a81cb6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.\nStacktrace:\nUnknownCommandError: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.\n    at catch404Handler (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\express\\middleware.js:139:49)\n    at Layer.handleRequest (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:435:11)\n    at Layer.handleRequest (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\lib\\layer.js:152:17)\n    at C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:295:15\n    at param (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:600:14)\n    at param (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:610:14)\n    at processParams (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:664:3)\n    at next (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:291:5)\n    at logger (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\morgan\\index.js:144:5)\n    at Layer.handleRequest (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\lib\\layer.js:152:17)\n    at trimPrefix (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:342:13)\n    at C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:297:9\n    at processParams (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:582:12)\n    at next (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\router\\index.js:291:5)\n    at C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\body-parser\\lib\\read.js:132:5\n    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)\n    at invokeCallback (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\pc\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\raw-body\\index.js:287:7)\n", "trace": "  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\pc\\Desktop\\Challenge Gaston Ferreyra\\Mobile-test\\conftest.py\", line 36, in driver\n    driver_instance = Remote(command_executor=command_executor, options=opts)  # âœ…\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 249, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 263, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 342, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1759482256442, "stop": 1759482256458}], "start": 1759482256441, "stop": 1759482256560}